### ISSUE TITLE
Feature:  Add center component for additional project info

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/TrackMyTime7#45]
### Between Project and Time Entry,
Have a narrow pane which shows some of the selected Projects' meta data that is not filled out in the form.

Maybe can include link to where to find task information.

**Comment by McDKirra** [comment]
Have ability to have more than one activity link

![5EB5989F](https://user-images.githubusercontent.com/35781691/77341546-8b8b1c00-6d37-11ea-9a2f-aff6d039c1ee.PNG)

**Comment by mikezimm** [comment]
Closed with PR #61 

Added ability to use semi-colon separated "Activity" field text to add more than one item...

Example:
Activity Type:  Build
Activity:  44;45

This will create 2 links... one for item 44 and one for item 45.
At the moment this does not hide the Activity field on the form.

How it works though is that if you do NOT click either of the links, it will create the Activity link based on the first one in your list.

However, if you click on one, the ActivityURL in the TrackMyTime item will actually link back to the one you last clicked before hitting save.
