### ISSUE TITLE
More colors!

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/TrackMyTime7#53]
Hey!

It would be easier to have project colors so it's easier to identify them in a second. Also would help cut back some of the whiteness which can be hard on the eyes. Thanks!

**Comment by mikezimm** [comment]
Wow what a coincidence!
Check out the latest pull request on Master...
https://github.com/mikezimm/TrackMyTime7/commit/13f9a204c19aef34616c15b7225183bf57372e05

First screenshot shows an example... hope it meets your needs.  While I was in there I added Font Color, Background Color, Font-size, Font-style and even the Fabric Icons :)

Second screenshot shows instructions in the webpart on how to get those results.  Oh and the List Provisioning now adds the Calculated options column out of the box as an example.

## Sample of new styling options per project item
![image](https://user-images.githubusercontent.com/49648086/75174255-46ef6f00-56fe-11ea-877a-30a23abfa2ba.png)

## How to get in-webpart help for the new options
![image](https://user-images.githubusercontent.com/49648086/75174289-52db3100-56fe-11ea-8d47-fd9d19e25ea7.png)
