### ISSUE TITLE
Missing info in Project ID 1 and 2

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/TrackMyTime7#74]
There should be something in project ID 1 and 2 but these are empty for some items as seen below. This may have something to do with project ID being a special.

<img width="851" alt="2020-06-01 20_35_02-Mike Zimmerman" src="https://user-images.githubusercontent.com/35781691/83437560-a4573280-a448-11ea-9d32-6ae3c223b45a.png">

<img width="471" alt="2020-06-01 20_36_36-" src="https://user-images.githubusercontent.com/35781691/83437574-a7eab980-a448-11ea-867e-7b90d19eb7a4.png">

**Comment by mikezimm** [comment]
Fixed all these now.
Thanks for testing!

**Comment by mikezimm** [comment]
If you want to do further confirmation testing, try this branch.

![image](https://user-images.githubusercontent.com/49648086/83568694-6d892700-a4f1-11ea-8d2e-f8c6abda69a9.png)

Make sure you see/use this commit:
![image](https://user-images.githubusercontent.com/49648086/83568781-90b3d680-a4f1-11ea-8e40-4d31913b3e0a.png)
