### ISSUE TITLE
Project ID1 info missing

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/TrackMyTime7#75]
Project ID1 info missing in some items as discussed and seen below

![12](https://user-images.githubusercontent.com/35781691/83562264-f455f800-a521-11ea-8a0e-dcd94bce52c3.jpg)
![3](https://user-images.githubusercontent.com/35781691/83562266-f5872500-a521-11ea-9749-4504d3f43fef.jpg)

**Comment by mikezimm** [comment]
Fixed this in this commit:

https://github.com/mikezimm/TrackMyTime7/commit/9ea260d7deef3ae9f8020bae831d5eae44b85104
