### ISSUE TITLE
Email summary/details from webpart

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/TrackMyTime7#9]
**Add email feature from within webpart**
From a "Report" type of page which sums up your hours per week/day with other gamification, have button to email yourself or others in AD a summary and or details of your tasks.

Maybe have a slider to select how many days to send.
Also maybe have an option to pick "This week", "Last week","This month" etc...

**Comment by McDKirra** [comment]
[https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0](url)

[https://docs.microsoft.com/en-us/graph/api/notifications-post?view=graph-rest-beta](url)

**Comment by mikezimm** [comment]
@McDKirra ,
Had a follow up idea to this one...
Have it be able to post updates to a Teams channel.
Need to understand graph api and find example but maybe in one of the recent SIG calls it was discussed.

**Comment by mikezimm** [comment]
Here's the pnp library where you can email using PnpJS:
https://pnp.github.io/pnpjs/sp/sp-utilities-utility/#sendemail

**Comment by mikezimm** [comment]
@McDKirra 
I'm going to close this one since the purchase of NitroStudios... not really needed in webpart any more.
